export const influencers = [
  {
    id: 1,
    handle: "@communikay",
    name: "Sophie Laurent",
    profilePicture: "/confident-gaze.png",
    location: "Arcachon",
    lat: 44.6635,
    lon: -1.1651,
    followers: 20000,
    engagementRate: 0.08,
    audience: {
      geography: { Arcachon: 70, Bordeaux: 20, Paris: 10 },
      interests: { speaking: 80, leadership: 60, events: 50 },
    },
    segments: { "Leadership Enthusiasts": 40, "Event Attendees": 30, Professionals: 20 },
    excerpt: "Hosting a communication workshop in Arcachon this October—join us!",
    sentiment: { communication: 0.95 },
    predictedPerformance: { impressions: 20000, engagement: 0.08, roi: 4 },
    topics: ["communication", "leadership", "events"],
    platforms: {
      YouTube: { views: 6000, engagement: 0.07 },
      TikTok: { views: 9000, engagement: 0.09 },
      Instagram: { likes: 5000, engagement: 0.08 },
    },
    cost: 800,
  },
  {
    id: 2,
    handle: "@tokyoTrendsetter",
    name: "Aiko Tanaka",
    profilePicture: "/serene-asian-portrait.png",
    location: "Tokyo",
    lat: 35.6762,
    lon: 139.6503,
    followers: 12000,
    engagementRate: 0.06,
    audience: {
      geography: { Tokyo: 70, Osaka: 20, Kyoto: 5 },
      interests: { sustainable_fashion: 60, streetwear: 40, beauty: 30 },
    },
    segments: { "Fashion Forward Gen Z": 50, "Streetwear Fans": 30, "Beauty Lovers": 15 },
    excerpt: "Sustainable fashion is the future—rocking this look in Tokyo!",
    sentiment: { sustainable_fashion: 0.85 },
    predictedPerformance: { impressions: 15000, engagement: 0.06, roi: 2.5 },
    topics: ["sustainable fashion", "streetwear", "beauty"],
    platforms: {
      YouTube: { views: 4000, engagement: 0.05 },
      TikTok: { views: 6000, engagement: 0.07 },
      Instagram: { likes: 3000, engagement: 0.06 },
    },
    cost: 400,
  },
  {
    id: 3,
    handle: "@sydneyGreenVibe",
    name: "Emma Wilson",
    profilePicture: "/curly-haired-contemplation.png",
    location: "Sydney",
    lat: -33.8688,
    lon: 151.2093,
    followers: 18000,
    engagementRate: 0.08,
    audience: {
      geography: { Sydney: 65, Melbourne: 25, Brisbane: 5 },
      interests: { sustainable_fashion: 70, wellness: 50, fitness: 20 },
    },
    segments: { "Wellness Warriors": 35, "Eco-Conscious Millennials": 35, "Fitness Buffs": 20 },
    excerpt: "Sustainable fashion haul for a sunny Sydney day!",
    sentiment: { sustainable_fashion: 0.92 },
    predictedPerformance: { impressions: 25000, engagement: 0.08, roi: 3.5 },
    topics: ["sustainable fashion", "wellness", "fitness"],
    platforms: {
      YouTube: { views: 6000, engagement: 0.07 },
      TikTok: { views: 9000, engagement: 0.09 },
      Instagram: { likes: 5000, engagement: 0.08 },
    },
    cost: 600,
  },
  {
    id: 4,
    handle: "@parisEcoChic",
    name: "Clara Dubois",
    profilePicture: "/chic-french-bob.png",
    location: "Paris",
    lat: 48.8566,
    lon: 2.3522,
    followers: 14000,
    engagementRate: 0.065,
    audience: {
      geography: { Paris: 70, Lyon: 15, Marseille: 10 },
      interests: { sustainable_fashion: 75, beauty: 40, travel: 25 },
    },
    segments: { "Fashion Enthusiasts": 40, "Eco-Conscious Millennials": 30, "Travel Lovers": 20 },
    excerpt: "Embracing sustainable fashion in the heart of Paris!",
    sentiment: { sustainable_fashion: 0.88 },
    predictedPerformance: { impressions: 18000, engagement: 0.065, roi: 2.8 },
    topics: ["sustainable fashion", "beauty", "travel"],
    platforms: {
      YouTube: { views: 4500, engagement: 0.06 },
      TikTok: { views: 7000, engagement: 0.08 },
      Instagram: { likes: 3500, engagement: 0.07 },
    },
    cost: 450,
  },
  {
    id: 5,
    handle: "@mumbaiGreenSoul",
    name: "Riya Patel",
    profilePicture: "/serene-indian-woman.png",
    location: "Mumbai",
    lat: 19.076,
    lon: 72.8777,
    followers: 16000,
    engagementRate: 0.075,
    audience: {
      geography: { Mumbai: 60, Delhi: 20, Bangalore: 15 },
      interests: { sustainable_fashion: 65, eco_living: 45, food: 30 },
    },
    segments: { "Eco-Conscious Millennials": 35, Foodies: 30, "Urban Dwellers": 25 },
    excerpt: "Sustainable fashion vibes in Mumbai's bustling streets!",
    sentiment: { sustainable_fashion: 0.9 },
    predictedPerformance: { impressions: 22000, engagement: 0.075, roi: 3.2 },
    topics: ["sustainable fashion", "eco living", "food"],
    platforms: {
      YouTube: { views: 5500, engagement: 0.07 },
      TikTok: { views: 8500, engagement: 0.09 },
      Instagram: { likes: 4500, engagement: 0.08 },
    },
    cost: 550,
  },
]
