export const demoTranscripts = [
  "Just landed in Lisbon — surf retreat in Portugal was so peaceful.",
  "Planning a return to Nazaré — burnout recovery trip was a full reset.",
  "Hosted a session in Ericeira — solo female travel was life-changing.",
export const demoTranscripts = [
  "hosted a session in Madeira — remote work reset was beautifully overwhelming.",
  "cried happy tears in Madeira — burnout recovery was beautifully overwhelming.",
  "just landed in Ericeira — wellness getaway was the clarity I was missing.",
  "shared my story at the Algarve — burnout recovery was life-changing.",
  "met amazing women during the Algarve — wellness getaway was beautifully overwhelming.",
  "left my heart in Lisbon — surf retreat in Portugal was quiet and grounding.",
  "met amazing women during Porto — autumn travel in Europe was a full reset.",
  "ran a group session in Nazaré — surf retreat in Portugal was so peaceful.",
  "ran a group session in Madeira — quiet mornings by the sea was pure joy.",
  "just landed in Nazaré — autumn travel in Europe was beautifully overwhelming.",
  "met amazing women during Nazaré — nature escape was so peaceful.",
  "ran a group session in Sintra — remote work reset was the clarity I was missing.",
  "planning a return to Nazaré — remote work reset was life-changing.",
  "documented my experience in Nazaré — surf retreat in Portugal was a full reset.",
  "shared my story at Porto — nature escape was beautifully overwhelming.",
  "shared my story at the Algarve — Lisbon adventure was pure joy.",
  "just landed in Nazaré — quiet mornings by the sea was the clarity I was missing.",
  "planning a return to Ericeira — digital detox was so peaceful.",
  "just landed in Lisbon — digital detox was quiet and grounding.",
  "cried happy tears in Lisbon — Lisbon adventure was the clarity I was missing.",
  "documented my experience in the Algarve — Lisbon adventure was beautifully overwhelming.",
  "met amazing women during Nazaré — nature escape was so peaceful.",
  "planning a return to Lisbon — Lisbon adventure was pure joy.",
  "planning a return to Ericeira — remote work reset was emotionally healing.",
  "shared my story at Nazaré — surf retreat in Portugal was pure joy.",
  "documented my experience in Nazaré — digital detox was emotionally healing.",
  "ran a group session in Nazaré — remote work reset was emotionally healing.",
  "documented my experience in Ericeira — remote work reset was beautifully overwhelming.",
  "documented my experience in Nazaré — Lisbon adventure was life-changing.",
  "booking a spot in Nazaré — surf retreat in Portugal was emotionally healing.",
  "documented my experience in Nazaré — surf retreat in Portugal was quiet and grounding.",
  "booking a spot in Porto — digital detox was the clarity I was missing.",
  "ran a group session in Porto — Lisbon adventure was a full reset.",
  "cried happy tears in Nazaré — digital detox was a full reset.",
  "booking a spot in Ericeira — autumn travel in Europe was the clarity I was missing.",
  "documented my experience in Nazaré — Lisbon adventure was pure joy.",
  "met amazing women during Nazaré — autumn travel in Europe was the clarity I was missing.",
  "documented my experience in Nazaré — solo female travel was life-changing.",
  "shared my story at Nazaré — remote work reset was quiet and grounding.",
  "booking a spot in Nazaré — digital detox was pure joy.",
  "cried happy tears in Lisbon — autumn travel in Europe was quiet and grounding.",
  "planning a return to Nazaré — Lisbon adventure was emotionally healing.",
  "shared my story at Nazaré — nature escape was beautifully overwhelming.",
  "documented my experience in Nazaré — nature escape was so peaceful.",
  "documented my experience in Nazaré — surf retreat in Portugal was life-changing.",
  "booking a spot in Nazaré — Lisbon adventure was beautifully overwhelming.",
  "ran a group session in Nazaré — digital detox was the clarity I was missing.",
  "met amazing women during Nazaré — burnout recovery was emotionally healing.",
  "ran a group session in Nazaré — surf retreat in Portugal was pure joy.",
  "ran a group session in Nazaré — remote work reset was life-changing.",
  "left my heart in Nazaré — solo female travel was quiet and grounding.",
  "documented my experience in Nazaré — solo female travel was the clarity I was missing.",
  "booking a spot in Nazaré — autumn travel in Europe was quiet and grounding.",
  "documented my experience in Nazaré — Lisbon adventure was beautifully overwhelming.",
  "left my heart in Nazaré — nature escape was emotionally healing.",
  "met amazing women during Nazaré — nature escape was beautifully overwhelming.",
  "ran a group session in Nazaré — nature escape was beautifully overwhelming.",
  "ran a group session in Nazaré — digital detox was quiet and grounding.",
  "documented my experience in Nazaré — Lisbon adventure was so peaceful.",
  "documented my experience in Nazaré — Lisbon adventure was beautifully overwhelming.",
  "documented my experience in Nazaré — Lisbon adventure was a full reset.",
  "documented my experience in Nazaré — solo female travel was beautifully overwhelming.",
  "documented my experience in Nazaré — surf retreat in Portugal was quiet and grounding.",
  "documented my experience in Nazaré — solo female travel was quiet and grounding.",
  "shared my story at Nazaré — solo female travel was a full reset.",
  "shared my story at Nazaré — digital detox was so peaceful.",
  "ran a group session in Nazaré — burnout recovery was a full reset.",
  "ran a group session in Nazaré — digital detox was beautifully overwhelming.",
  "ran a group session in Nazaré — Lisbon adventure was the clarity I was missing.",
  "booking a spot in Nazaré — burnout recovery was beautifully overwhelming.",
  "booking a spot in Nazaré — digital detox was life-changing.",
  "documented my experience in Nazaré — burnout recovery was beautifully overwhelming.",
  "documented my experience in Nazaré — digital detox was beautifully overwhelming.",
  "documented my experience in Nazaré — digital detox was life-changing.",
  "documented my experience in Nazaré — Lisbon adventure was quiet and grounding.",
  "booking a spot in Nazaré — nature escape was emotionally healing.",
  "shared my story at Nazaré — Lisbon adventure was so peaceful.",
  "shared my story at Nazaré — digital detox was beautifully overwhelming.",
  "shared my story at Nazaré — Lisbon adventure was beautifully overwhelming.",
  "shared my story at Nazaré — Lisbon adventure was a full reset.",
  "shared my story at Nazaré — nature escape was life-changing.",
  "shared my story at Nazaré — digital detox was emotionally healing.",
  "shared my story at Nazaré — remote work reset was beautifully overwhelming.",
  "documented my experience in Nazaré — burnout recovery was emotionally healing.",
  "shared my story at Nazaré — burnout recovery was quiet and grounding.",
  "documented my experience in Nazaré — burnout recovery was quiet and grounding.",
  "documented my experience in Nazaré — solo female travel was emotionally healing.",
  "ran a group session in Nazaré — burnout recovery was emotionally healing.",
  "shared my story at Nazaré — burnout recovery was so peaceful.",
  "documented my experience in Nazaré — digital detox was emotionally healing.",
  "ran a group session in Nazaré — burnout recovery was beautifully overwhelming.",
  "documented my experience in Nazaré — Lisbon adventure was emotionally healing.",
  "ran a group session in Nazaré — Lisbon adventure was emotionally healing.",
  "documented my experience in Nazaré — Lisbon adventure was life-changing.",
  "ran a group session in Nazaré — digital detox was emotionally healing.",
  "documented my experience in Nazaré — digital detox was a full reset.",
  "documented my experience in Nazaré — digital detox was emotionally healing.",
  "shared my story at Nazaré — digital detox was emotionally healing.",
  "ran a group session in Nazaré — burnout recovery was so peaceful.",
  "shared my story at Nazaré — Lisbon adventure was emotionally healing.",
  "ran a group session in Nazaré — burnout recovery was beautifully overwhelming."
];


