import csv

# Full list of terms (deduplicated)
terms = [
    "abbo", "abeed", "acrotomophilia", "aeolus", "africoon", "ahole", 
"alabamahotpocket",
    "alaskanpipeline", "alligatorbait", "amcik", "anal", "analannie", 
"analprobe", "analsex",
    "andskota", "anilingus", "anus", "apeshit", "arabush", "arabushs", 
"areola", "areole",
    "argie", "armo", "armos", "aroused", "arrse", "arschloch", "arse", 
"arsehole", "aryan",
    "asholes", "ass", "ass-fucker", "ass-hat", "ass-pirate", "assbag", 
"assbagger", "assbandit",
    "assbang", "assbanged", "assbanger", "assbangs", "assbite", 
"assblaster", "assclown",
    "asscock", "asscowboy", "asscracker", "asses", "assface", "assfuck", 
"assfucker", "assfukka",
    "assgoblin", "asshat", "asshead", "assho1e", "asshole", "assholes", 
"assholz", "asshopper",
    "asshore", "assjacker", "assjockey", "asskiss", "asskisser", 
"assklown", "asslick",
    "asslicker", "asslover", "assman", "assmaster", "assmonkey", 
"assmunch", "assmuncher",
    "assnigger", "asspacker", "asspirate", "asspuppies", "assrammer", 
"assranger", "assshit",
    "asssucker", "asswad", "asswhole", "asswhore", "asswipe", "asswipes", 
"autoerotic", "ayir",
    "azazel", "azz", "azzhole", "babeland", "babes", "babybatter", 
"babyjuice", "backdoor",
    "backdoorman", "badfuck", "bagging", "ballgag", "ballgravy", 
"ballkicking", "balllicking",
    "ballsack", "ballsucking", "ballbag", "balllicker", "bampot", 
"bangbro", "bangbros",
    "bangbus", "banger", "banging", "bareback", "barenaked", "barface", 
"barfface", "bassterd",
    "bassterds", "bastard", "bastardo", "bastards", "bastardz", 
"basterds", "bastinado", "bawdy",
    "bazongas", "bazooms", "bbw", "bdsm", "beaner", "beaners", "beaney", 
"beaneys", "beardedclam",
    "beastality", "beastial", "beastiality", "beastility", "beatch", 
"beatoff", "beatyourmeat",
    "beavercleaver", "beaverlips", "beefcurtains", "beeyotch", "bellend", 
"beotch", "berk",
    "bestial", "bestiality", "biatch", "bigblack", "bigbreasts", 
"bigknockers", "bigtits",
    "bigass", "bigbastard", "bigbutt", "bimbo", "bimbos", "bint", 
"birdlock", "bitch", "bitchass",
    "bitched", "bitcher", "bitchers", "bitches", "bitchez", "bitchin", 
"bitching", "bitchslap",
    "bitchtit", "bitchy", "biteme", "bitties", "blackcock", "blackman", 
"blackout", "blacks",
    "blondeaction", "blondeonblondeaction", "blondeonblonde", 
"bloodclaat", "bloody", "blowj",
    "blowjob", "blowyourl", "blowyourload", "blowjobs", "bluewaffle", 
"bluegum", "bluegums",
    "blumpkin", "boang", "boche", "boches", "boffing", "bogan", "bohunk", 
"boink", "boiolas",
    "bollick", "bollock", "bollocks", "bollok", "bollox", "bombers", 
"bombing", "bondage", "boned",
    "boner", "boners", "bong", "bookie", "boong", "boonga", "boongas", 
"boongs", "boonie",
    "boonies", "bootee", "bootlip", "bootlips", "bosch", "bosche", 
"bosches", "boschs", "bosomy",
    "bountybar", "breastjob", "breastlover", "breastman", "brownshower", 
"brunetteaction", "buceta",
    "buddhahead", "buddhaheads", "buffies", "bugger", "buggered", 
"buggery", "bukake", "bukkake",
    "bullcrap", "bulldike", "bulldyke", "bulletvibe", "bullshit", 
"bullshits", "bullshitted",
    "bullturds", "bumblefuck", "bumfuck", "bunghole", "bung", "bunga", 
"bungas", "bunnyfucker",
    "burrhead", "butchbabes", "butchdike", "butchdyke", "buttplug", 
"butt-pirate", "buttbang",
    "buttcheeks", "buttface", "buttfuck", "buttfucker", "buttfuckers", 
"butthead", "butthole",
    "buttman", "buttmuch", "buttmunch", "buttmuncher", "buttpirate", 
"buttstain", "buttwipe",
    "byatch", "cunt", "c-0-c-k", "c-o-c-k", "c-u-n-t", "c.o.c.k.", 
"c.u.n.t", "cabron", "caca",
    "cacker", "cahone", "cameljockey", "cameljockeys", "cameltoe", 
"camgirl", "camslut", "camwhore",
    "carpetmuncher", "carruth", "cawk", "cawks", "cazzo", "cervix", 
"chav", "cheeseeatingsurrendermonkey",
    "cheeseeatingsurrendermonkies", "cheesehead", "cheeseheads", 
"cherrypopper", "chickslick",
    "chinaswede", "chinaswedes", "chinaman", "chinamen", "chinc", 
"chincs", "chingchong", "chingchongs",
    "chinga", "chink", "chinks", "chinky", "choad", "chocolaterosebuds", 
"chode", "chodes", "chonkies",
    "chonky", "chonkys", "chraa", "christkiller", "christkillers", "chug", 
"chugs", "chuj", "chunger",
    "chungers", "chunkies", "chunkys", "chute", "cipa", "circlejerk", 
"clamdigger", "clamdiver", "clamps",
    "clansman", "clansmen", "clanswoman", "clanswomen", 
"clevelandsteamer", "clit", "clitface", "clitfuck",
    "clitoris", "clitorus", "clits", "clitty", "clogwog", "cloverclamps", 
"clusterfuck", "cocain", "cocaine",
    "cock", "cock-head", "cock-sucker", "cockbite", "cockblock", 
"cockblocker", "cockburger", "cockcowboy",
    "cockface", "cockfight", "cockfucker", "cockhead", "cockholster", 
"cockjockey", "cockknob", "cockknocker",
    "cockknoker", "cocklicker", "cocklover", "cockmaster", "cockmongler", 
"cockmongruel", "cockmonkey",
    "cockmunch", "cockmuncher", "cocknob", "cocknose", "cocknugget", 
"cockqueen", "cockrider", "cocks",
    "cockshit", "cocksman", "cocksmith", "cocksmoker", "coccuntksucer", 
"cocksuck", "cocksucked", "cocksucker",
    "cocksucking", "cocksucks", "cocksuka", "cocksukka", "cocktease", 
"cocky", "cockwomble", "cohee", "coital",
    "coitus", "commie", "coochie", "coochy", "coolie", "coolies", "cooly", 
"coonass", "coonasses", "coondog",
    "coons", "cooter", "coprolagnia", "coprophilia", "copulate", 
"corksucker", "cornhole", "crackcocain",
    "cracker", "crackpipe", "crackwhore", "crap", "crapola", "crapper", 
"crappy", "creampie", "crotch",
    "crotchjockey", "crotchmonkey", "crotchrot", "cuck", "cumface", 
"cumlicker", "cum", "cumbubble",
    "cumdumpster", "cumfest", "cumguzzler", "cuming", "cumjockey", "cumm", 
"cummer", "cummin", "cumming",
    "cumquat", "cumqueen", "cums", "cumshot", "cumshots", "cumslut", 
"cumstain", "cumsucker", "cumtart",
    "cunilingus", "cunillingus", "cunn", "cunnie", "cunnilingus", 
"cunntt", "cunny", "cunteyed", "cuntface",
    "cuntfuck", "cuntfucker", "cunthole", "cunthunter", "cuntlick", 
"cuntlicker", "cuntlicking", "cuntrag",
    "cunts", "cuntslut", "cuntsucker", "cuntz", "currymuncher", 
"currymunchers", "cushi", "cushis", "cyalis",
    "cyberfuck", "cyberfucked", "cyberfucker", "cyberfuckers", 
"cyberfucking", "cybersex", "cyberslimer",
    "dago", "dagos", "dahmer", "damm", "dammit", "damn", "damnation", 
"damned", "damnit", "darkey", "darkeys",
    "darkie", "darkies", "darky", "daterape", "datnigga", "dawgiestyle", 
"dawgie-style", "daygo", "deapthroat",
    "deepthroat", "deepthroating", "deepaction", "defecate", "deggo", 
"dego", "degos", "demon", "dendrophilia",
    "diaperdaddy", "diaperhead", "diaperheads", "dickpic", "dick", 
"dick-ish", "dickbag", "dickbeater",
    "dickbeaters", "dickbrain", "dickdipper", "dickface", "dickflipper", 
"dickforbrains", "dickfuck", "dickhead",
    "dickheads", "dickhole", "dickish", "dickjuice", "dickless", 
"dicklick", "dicklicker", "dickman", "dickmilk",
    "dickmonger", "dickripper", "dicks", "dicksipper", "dickslap", 
"dickslicker", "dicksucker", "dickwad",
    "dickweasel", "dickweed", "dickwhipper", "dickwod", "dickzipper", 
"diddle", "dike", "dildo", "dildos",
    "dilf", "diligaf", "dillweed", "dimwit", "dingle", "dingleberries", 
"dingleberry", "dink", "dinks", "dipship",
    "dipshit", "dipstick", "dirsa", "dirtypillows", "dirtysanchez", "dix", 
"dixiedike", "dixiedyke", "dlck",
    "dogstyle", "dog-fucker", "doggiestyle", "doggie", "doggie-style", 
"doggin", "dogging", "doggystyle",
    "doggy-style", "dolcett", "domination", "dominatricks", "dominatrics", 
"dominatrix", "dommes", "dong",
    "donkeypunch", "donkeyribber", "doochbag", "doodoo", "doofus", 
"dookie", "doosh", "dothead", "dotheads",
    "doubledong", "doublepenetration", "douchebag", "douche", 
"douche-fag", "douchebags", "douchewaffle",
    "douchey", "dpaction", "dragqueen", "dragqween", "dripdick", 
"dryhump", "duche", "dudette", "dumass",
    "dumbass", "dumbasses", "dumbbitch", "dumbfuck", "dumbshit", 
"dumshit", "dunecoon", "dunecoons", "dupa",
    "dvda", "dyefly", "dyke", "dykes", "dziwka", "earotics", "easyslut", 
"eatmyass", "eatmy", "eatadick",
    "eatballs", "eathairpie", "eatme", "eatpussy", "ecchi", "ejackulate", 
"ejakulate", "ekrem", "ekto",
    "enculer", "enema", "enlargement", "erect", "erection", "erotic", 
"erotism", "escort", "esqua", "essohbee",
    "ethicalslut", "excrement", "exkwew", "extacy", "extasy", "fucker", 
"fucke", "fuck", "fuk", "f-u-c-k",
    "f.u.c.k", "f_u_c_k", "facefucker", "fack", "faeces", "faen", "fag", 
"fagbag", "faget", "fagfucker", "fagg",
    "fagged", "fagging", "faggit", "faggitt", "faggot", "faggotcock", 
"faggs", "fagit", "fagot", "fagots",
    "fags", "fagt", "fagtard", "fagz", "faig", "faigs", "faigt", 
"fanculo", "fannybandit", "fannyflaps",
    "fannyfucker", "fanyy", "fartknocker", "fastfuck", "fatah", "fatfuck", 
"fatfucker", "fatso", "fecal",
    "feck", "fecker", "felatio", "felch", "felcher", "felching", 
"fellate", "fellatio", "feltch", "feltcher",
    "feltching", "femalesquirting", "femalesquirtin", "femdom", "fetish", 
"ficken", "figging", "fingerbang",
    "fingerfuck", "fingerfucked", "fingerfucker", "fingerfuckers", 
"fingerfucking", "fingerfucks", "fingering",
    "fisted", "fister", "fistfuck", "fistfucked", "fistfucker", 
"fistfuckers", "fistfucking", "fistfuckings",
    "fistfucks", "fisting", "fisty", "flamer", "flange", "flasher", 
"flikker", "flippingthebird", "flogthelog",
    "floozy", "flydie", "flydye", "foobar", "fook", "fooker", 
"footfetish", "footaction", "footfuck", "footfucker",
    "footjob", "footlicker", "footstar", "foreskin", "forni", "fornicate", 
"fotze", "foursome", "freakfuck",
    "freakyfucker", "freefuck", "freex", "frigg", "frigga", "frigger", 
"frotting", "fucck", "fuck-tard", "fucka",
    "fuckable", "fuckass", "fuckbag", "fuckbitch", "fuckbook", "fuckboy", 
"fuckbrain", "fuckbuddy", "fuckbutt",
    "fucked", "fuckedup", "fuckers", "fuckersucker", "fuckface", 
"fuckfest", "fuckfreak", "fuckfriend", "fuckhead",
    "fuckheads", "fuckher", "fuckhole", "fuckin", "fuckina", "fucking", 
"fuckingbitch", "fuckings", "fuckingshitmotherfucker",
    "fuckinnuts", "fuckinright", "fuckit", "fuckknob", "fuckme", 
"fuckmeat", "fuckmonkey", "fucknugget", "fucknut",
    "fucknuts", "fucknutt", "fucknutz", "fuckoff", "fuckpig", 
"fuckpuppet", "fucks", "fuckstick", "fucktard",
    "fucktards", "fucktoy", "fucktrophy", "fuckup", "fuckwad", "fuckwhit", 
"fuckwhore", "fuckwit", "fuckwitt",
    "fuckyomama", "fuckyou", "fudgepacker", "fugly", "fukah", "fuken", 
"fuker", "fukin", "fuking", "fukk",
    "fukkah", "fukken", "fukker", "fukkin", "fukking", "fuks", "fuktard", 
"fuktards", "fukwhit", "fukwit",
    "funfuck", "gangbang", "gangbanged", "gangbanger", "gangbangs", 
"gangsta", "ganja", "gassyass", "gatorbait",
    "gaysex", "gayass", "gaybob", "gayboy", "gaydo", "gaygirl", "gaylord", 
"gays", "gaytard", "gaywad", "gayz",
    "geezer", "geni", "genital", "genitals", "getiton", "giantcock", 
"gigolo", "ginzo", "ginzos", "gipp", "gippo",
    "gippos", "gipps", "girlontop", "girlon", "girlsgonewild", "givehead", 
"glans", "glazeddonut", "goatcx",
    "goatse", "gokkun", "goldenshower", "golliwog", "golliwogs", "gonad", 
"gonads", "gonorrehea", "gonzagas",
    "googirl", "gooch", "goodpoop", "gookeye", "gookeyes", "gook", 
"gookies", "gooks", "gooky", "gora", "goras",
    "goregasm", "gotohell", "goy", "goyim", "greaseball", "greaseballs", 
"groe", "groid", "groids", "grope",
    "grostulation", "groupsex", "gspot", "gstring", "gtfo", "gub", 
"gubba", "gubbas", "gubs", "guido", "guiena",
    "guineas", "guizi", "gummer", "guro", "gwailo", "gwailos", "gweilo", 
"gweilos", "gyopo", "gyopos", "gyp",
    "gyped", "gypo", "gypos", "gypp", "gypped", "gyppie", "gyppies", 
"gyppo", "gyppos", "gyppy", "gyppys",
    "gypsys", "hell", "hom", "hadji", "hadjis", "hairyback", "hairybacks", 
"haji", "hajis", "hajji", "hajjis",
    "halfbreed", "halfcaste", "hamas", "hamflap", "handjob", "haole", 
"haoles", "hapa", "hardcore", "hardcoresex",
    "hardon", "harem", "headfuck", "hebe", "hebes", "heeb", "heebs", 
"hells", "helvete", "hentai", "heroin",
    "herp", "herpes", "herpy", "heshe", "hijacker", "hijacking", 
"hillbillies", "hillbilly", "hindoo", "hiscock",
    "hitler", "hitlerism", "hitlerist", "hoar", "hoare", "hobag", 
"hodgie", "hoe", "hoer", "hoes", "holestuffer",
    "hom0", "homey", "homo", "homobangers", "homodumbshit", "homoey", 
"honger", "honkers", "honkey", "honkeys",
    "honkie", "honkies", "honky", "hooch", "hooker", "hookers", "hoor", 
"hoore", "hootch", "hooter", "hooters",
    "hore", "hori", "horis", "hork", "horndawg", "horndog", "horney", 
"horniest", "horny", "horseshit", "hosejob",
    "hoser", "hotcarl", "hotchick", "hotdamn", "hotpussy", "hotsex", 
"howtomurder", "howtokill", "howtomurdep",
    "huevon", "hugefat", "humped", "humper", "humpher", "humphim", 
"humpin", "humping", "hussy", "hustler",
    "hymen", "hymie", "hymies", "incest", "indon", "indons", "injun", 
"injuns", "insest", "intercourse",
    "interracial", "israels", "jackoff", "jack-off", "jackass", 
"jackhole", "jackshit", "jacktheripper", "jailbait",
    "jap", "japcrap", "japie", "japies", "japs", "jebus", "jellydonut", 
"jerkoff", "jerk", "jerk-off", "jerk0ff",
    "jerked", "jerries", "jerry", "jewboy", "jewed", "jewess", "jiga", 
"jigaboo", "jigaboos", "jigarooni",
    "jigaroonis", "jigg", "jigga", "jiggabo", "jiggaboo", "jiggabos", 
"jiggas", "jigger", "jiggerboo", "jiggers",
    "jiggs", "jiggy", "jigs", "jihad", "jijjiboo", "jijjiboos", "jimfish", 
"jisim", "jism", "jiss", "jiz",
    "jizim", "jizin", "jizjuice", "jizm", "jizn", "jizz", "jizzed", 
"jizzim", "jizzin", "jizzn", "jizzum",
    "jugg", "juggs", "jugs", "junglebunny", "junkie", "junky", "kacap", 
"kacapas", "kacaps", "kaffer", "kaffir",
    "kaffre", "kafir", "kanake", "kanker", "katsap", "katsaps", "kawk", 
"khokhol", "khokhols", "kicking", "kigger",
    "kike", "kikes", "kimchis", "kinbaku", "kink", "kinkster", "kinky", 
"kinkyjesus", "kissass", "kiunt", "kkk",
    "klan", "klansman", "klansmen", "klanswoman", "klanswomen", 
"klootzak", "knobbing", "knobead", "knobed",
    "knobend", "knobhead", "knobjocky", "knobjokey", "knobz", "knockers", 
"knulle", "kock", "kondum", "kondums",
    "kooch", "kooches", "koon", "kootch", "krap", "krappy", "kraut", 
"krauts", "kuffar", "kuk", "kuksuger",
    "kum", "kumbubble", "kumbullbe", "kumer", "kummer", "kumming", 
"kumquat", "kums", "kunilingus", "kunnilingus",
    "kunt", "kunts", "kuntz", "kurac", "kurwa", "kushi", "kushis", "kusi", 
"kwa", "kwailo", "kwailos", "kwif",
    "kyke", "kykes", "kyopo", "kyopos", "kyrpa", "labia", "lapdance", 
"leatherrestraint", "leatherstraight",
    "lebos", "lech", "lemonparty", "leper", "lesbain", "lesbayn", 
"lesbin", "lesbo", "lesbos", "lez", "lezbe",
    "lezbefriends", "lezbian", "lezbians", "lezbo", "lezbos", "lezz", 
"lezzian", "lezzie", "lezzies", "lezzo",
    "lezzy", "limey", "limpdick", "limy", "lipshits", "lipshitz", 
"livesex", "loadedgun", "loin", "loins",
    "lolita", "lovebone", "lovegoo", "lovegun", "lovejuice", "lovemaking", 
"lovemuscle", "lovepistol", "loverocket",
    "lowlife", "lsd", "lubejob", "lubra", "lucifer", "lugan", "lugans", 
"lust", "lusting", "lusty", "mabuno",
    "mabunos", "macaca", "macacas", "mafugly", "magicwand", "mahbuno", 
"mahbunos", "makemecome", "malesquirting",
    "mamhoon", "mams", "manhater", "manpaste", "maricon", "marijuana", 
"masochist", "masokist", "massa", "mastabate",
    "mastabater", "master-bate", "masterbaiter", "masterbat", 
"masterbate", "masterbates", "masterbating",
    "masterbation", "masterbations", "masterblaster", "mastrabator", 
"masturbat", "masturbate", "masturbating",
    "masturbation", "mattressprincess", "maumau", "maumaus", "mcfagget", 
"meatbeatter", "meatrack", "menage",
    "merd", "mibun", "mick", "mickeyfinn", "mideast", "mierda", "milf", 
"minge", "minger", "mo-fo", "mockey",
    "mockie", "mocky", "mofo", "moky", "molest", "molestation", 
"molester", "molestor", "moneyshot", "mong",
    "monkleigh", "moolie", "mooncricket", "mormon", "moron", "moskal", 
"moskals", "moslem", "mosshead",
    "mothafucker", "mothafuck", "mothafucka", "mothafuckas", 
"mothafuckaz", "mothafucked", "mothafuckers",
    "mothafuckin", "mothafucking", "mothafuckings", "mothafucks", 
"motherfucker", "motherfukah", "motherfuker",
    "motherfukkah", "motherfukker", "mother-fucker", "motherfuck", 
"motherfucka", "motherfucked", "motherfuckers",
    "motherfuckin", "motherfucking", "motherfuckings", "motherfuckka", 
"motherfucks", "motherfvcker", "motherlovebone",
    "mothrfucker", "mouliewop", "moundofvenus", "muff", "muffdive", 
"muffdiver", "muffdiving", "muffindiver",
    "mufflikcer", "muffpuff", "muie", "mulatto", "mulkku", "muncher", 
"mung", "munging", "munt", "munter",
    "muschi", "muthafucker", "muthafukah", "muthafuker", "muthafukkah", 
"muthafukker", "muthafecker", "muthafuckaz",
    "muthafuckker", "muther", "mutherfucker", "mutherfucking", 
"muthrfucking", "mzungu", "mzungus", "nad", "nads",
    "naked", "nambla", "nappy", "nastt", "nawashi", "nazi", "nazis", 
"nazism", "necked", "necro", "negres",
    "negress", "negro", "negroes", "negroid", "negros", "neonazi", 
"nepesaurio", "nignog", "nig", "niga", "nigar",
    "nigars", "nigas", "nigers", "nigette", "nigettes", "nigg", "nigga", 
"niggah", "niggahs", "niggar", "niggaracci",
    "niggard", "niggarded", "niggarding", "niggardliness", "niggardly", 
"niggards", "niggars", "niggas", "niggaz",
    "nigger", "niggerhead", "niggerhole", "niggers", "niggle", "niggled", 
"niggles", "niggling", "nigglings",
    "niggor", "niggress", "niggresses", "nigguh", "nigguhs", "niggur", 
"niggurs", "niglet", "nigor", "nigors",
    "nigr", "nigra", "nigras", "nigre", "nigres", "nigress", "nigs", 
"nigur", "niiger", "niigr", "nimphomania",
    "nimrod", "ninny", "nip", "nipple", "nipplering", "nipples", "nips", 
"nittit", "nlgger", "nlggor", "nob",
    "nobhead", "nobjocky", "nobjokey", "nofuckingway", "nog", "nookey", 
"nookie", "nooky", "noonan", "nooner",
    "nsfwimages", "nsfw", "nudger", "nudie", "nudies", "numbnuts", 
"nutbutter", "nutfucker", "nutten", "nymph",
    "nympho", "nymphomania", "octopussy", "omorashi", "onecuptwogirls", 
"oneguyonejar", "oneguy", "onejar",
    "ontherag", "orafis", "orally", "orga", "orgasim", "orgasims", 
"orgasm", "orgasmic", "orgasms", "orgasum",
    "orgies", "orgy", "oriface", "orifice", "orifiss", "orospu", "osama", 
"ovum", "ovums", "penis", "pis",
    "pussy", "p.u.s.s.y.", "packi", "packie", "packy", "paddy", 
"paedophile", "paki", "pakie", "pakis", "paky",
    "palesimian", "pancakeface", "pancakefaces", "panooch", "pansies", 
"pansy", "panti", "pantie", "panties",
    "panty", "paska", "pastie", "pasty", "payo", "pcp", "pearlnecklace", 
"pecker", "peckerhead", "peckerwood",
    "pedo", "pedobear", "pedophile", "pedophilia", "pedophiliac", 
"peeenus", "peeenusss", "peehole", "peenus",
    "peepee", "peepshow", "peepshpw", "pegging", "peinus", "penas", 
"pendejo", "pendy", "penetrate", "penetration",
    "penial", "penile", "penis-breath", "penises", "penisfucker", 
"penisland", "penislick", "penislicker",
    "penispuffer", "penthouse", "penus", "penuus", "perse", "perv", 
"perversion", "peyote", "phalli", "phallic",
    "phonesex", "phuc", "phuck", "phuk", "phuked", "phuker", "phuking", 
"phukked", "phukker", "phukking", "phuks",
    "phungky", "phuq", "picaninny", "piccaninny", "picka", "pickaninnies", 
"pickaninny", "piefke", "piefkes",
    "pierdol", "pigfucker", "piker", "pikey", "piky", "pillowbiter", 
"pillu", "pimmel", "pimp", "pimped", "pimper",
    "pimpis", "pimpjuic", "pimpjuice", "pimpsimp", "pindick", "pinko", 
"pises", "pisin", "pising", "pisof",
    "pisspig", "piss", "piss-off", "pissed", "pisser", "pissers", 
"pisses", "pissflap", "pissflaps", "pisshead",
    "pissin", "pissing", "pissoff", "pistol", "pizda", "playboy", 
"playgirl", "pleasurechest", "pocha", "pochas",
    "pocho", "pochos", "pocketpool", "pohm", "pohms", "polac", "polack", 
"polacks", "polak", "polesmoker",
    "pollock", "pollocks", "pommiegrant", "pommiegrants", "pommy", 
"ponyplay", "poof", "poon", "poonani",
    "poonany", "poontang", "poontsee", "poopchute", "pooper", 
"pooperscooper", "pooping", "poorwhitetrash",
    "popimp", "porchmonkey", "porchmonkies", "porn", "pornflick", 
"pornking", "porno", "pornography", "pornos",
    "pornprincess", "poundtown", "pplicker", "prairienigger", 
"prairieniggers", "premature", "preteen", "prick",
    "prickhead", "pricks", "prig", "princealbertpiercing", "pron", 
"prostitute", "pthc", "pube", "pubes", "pubic",
    "pubiclice", "pubis", "pud", "pudboy", "pudd", "puddboy", "pula", 
"pule", "punani", "punanny", "punany",
    "punkass", "punky", "punta", "puntang", "purinapricness", "pusio", 
"pussio", "pusies", "puss", "pusse",
    "pussee", "pussi", "pussie", "pussies", "pussycat", "pussydestroyer", 
"pussyeater", "pussyfart", "pussyfucker",
    "pussylicker", "pussylicking", "pussylips", "pussylover", 
"pussypalace", "pussypounder", "pussys", "pusy",
    "puta", "puto", "puuke", "puuker", "qahbeh", "quashie", "queaf", 
"queef", "queerhole", "queero", "queers",
    "queerz", "quickie", "quicky", "quiff", "quim", "qweers", "qweerz", 
"qweir", "r-tard", "r-tards", "raghead",
    "ragheads", "rape", "raped", "raper", "raping", "rapist", 
"rautenberg", "rearend", "rearentry", "recktum",
    "rectal", "rectum", "rectus", "redleg", "redlegs", "redlight", 
"redneck", "rednecks", "redskin", "redskins",
    "reefer", "reestie", "reetard", "reich", "renob", "rentafuck", "rere", 
"retard", "retarded", "retards",
    "reversecowgirl", "rigger", "rimjaw", "rimjob", "rimming", "ritard", 
"rosebuds", "rosypalm", "roundeyes",
    "roundeye", "rumprammer", "ruski", "russki", "russkie", 
"rustytrombone", "shit", "sadism", "sadist", "sadom",
    "sambo", "sambos", "samckdaddy", "sandnigger", "sandniggers", "sandm", 
"santorum", "sausagequeen", "scag",
    "scallywag", "scank", "scantily", "scat", "schaffer", "scheiss", 
"schizo", "schlampe", "schlong", "schmuck",
    "schvartse", "schvartsen", "schwartze", "schwartzen", "scissoring", 
"scroat", "scrog", "scrote", "scrotum",
    "scrud", "semen", "seppo", "seppos", "septics", "sex", "sexcam", 
"sexed", "sexfarm", "sexhound", "sexhouse",
    "sexi", "sexing", "sexkitten", "sexo", "sexpot", "sexslave", 
"sextogo", "sextoy", "sextoys", "sexual",
    "sexually", "sexwhore", "sexymoma", "sexyslim", "shag", "shagger", 
"shaggin", "shagging", "shamedame",
    "sharmuta", "sharmute", "shat", "shav", "shavedbeaver", "shavedpussy", 
"shawtypimp", "sheeney", "shemale",
    "shibari", "shibary", "shinola", "shipal", "shitass", "shit-ass", 
"shit-bag", "shit-bagger", "shit-brain",
    "shit-breath", "shit-cunt", "shit-dick", "shit-eating", "shit-face", 
"shit-faced", "shit-fit", "shit-head",
    "shit-heel", "shit-hole", "shit-house", "shit-load", "shit-pot", 
"shit-spitter", "shit-stain", "shitbag",
    "shitbagger", "shitblimp", "shitbrain", "shitbreath", "shitcan", 
"shitcunt", "shitdick", "shite", "shiteater",
    "shiteating", "shited", "shitey", "shitface", "shitfaced", "shitfit", 
"shitforbrains", "shitfuck", "shitfucker",
    "shitfull", "shithapens", "shithappens", "shithead", "shitheel", 
"shithole", "shithouse", "shiting", "shitings",
    "shitlist", "shitload", "shitola", "shitoutofluck", "shitpot", 
"shits", "shitspitter", "shitstain", "shitt",
    "shitted", "shitter", "shitters", "shittiest", "shitting", 
"shittings", "shitty", "shity", "shitz", "shiz",
    "shiznit", "shortfuck", "shota", "shrimping", "shylock", "shylocks", 
"shyt", "shyte", "shytty", "shyty",
    "simp", "sissy", "sixsixsix", "sixtynine", "sixtyniner", "skag", 
"skanck", "skank", "skankbitch", "skankee",
    "skankey", "skankfuck", "skanks", "skankwhore", "skanky", 
"skankybitch", "skankywhore", "skeet", "skinflute",
    "skribz", "skullfuck", "skum", "skumbag", "skurwysyn", "skwa", "skwe", 
"slag", "slanteye", "slanty", "slapper",
    "sleezeball", "slideitin", "slimeball", "slimebucket", "slopehead", 
"slopeheads", "sloper", "slopers", "slopes",
    "slopey", "slopeys", "slopies", "slopy", "slut", "slutbag", 
"slutbucket", "slutdumper", "slutkiss", "sluts",
    "slutt", "slutting", "slutty", "slutwear", "slutwhore", "slutz", 
"smeg", "smegma", "smoker", "smut", "smutty",
    "snatchpatch", "snowback", "snowballing", "snownigger", "socksucker", 
"sodom", "sodomise", "sodomite",
    "sodomize", "sodomy", "sonofabitch", "sonofawhore", "son-of-a-bitch", 
"son-of-a-whore", "sooties", "sooty",
    "souse", "soused", "soyboy", "spac", "spade", "spades", "spank", 
"spastic", "spearchucker", "spearchuckers",
    "sperm", "spermacide", "spermbag", "spermhearder", "spermherder", 
"sphencter", "spic", "spick", "spicks",
    "spics", "spierdalaj", "spig", "spigotty", "spik", "spiks", "spitter", 
"splittail", "splooge", "spludge",
    "spooge", "spreadlegs", "spreadeagle", "spunk", "spunky", "sqeh", 
"squa", "squarehead", "squareheads", "squaw",
    "squinty", "squirting", "stagg", "steamy", "stfu", "stiffy", "stoned", 
"stoner", "strapon", "strappado",
    "stringer", "stripclub", "stroke", "stroking", "stuinties", 
"stupidfuck", "stupidfucker", "styledoggy",
    "suckdick", "sucked", "sucker", "sucking", "sucks", "suicidegirl", 
"suicidegirls", "suka", "sultrywoman",
    "sultrywomen", "sumofabiatch", "swallower", "swalow", "swampguinea", 
"swampguineas", "swastika", "syphilis",
    "taboo", "tacohead", "tacoheads", "taff", "takeoffyour", "tarbabies", 
"tarbaby", "tard", "tawdry", "teabagging",
    "teat", "teets", "teez", "terd", "terror", "terrorist", "teste", 
"testee", "testes", "testical", "testicle",
    "testicles", "testis", "thicklip", "thicklips", "thirdeye", 
"thirdleg", "threesome", "threeway", "throating",
    "thumbzilla", "thundercunt", "tightwhite", "timbernigger", "tinkle", 
"tit", "titfuck", "titfucker", "titfuckin",
    "titi", "titjob", "titlicker", "titlover", "tits", "titt", "tittie", 
"tittie5", "tittiefucker", "titties",
    "tittis", "titty", "tittyfuck", "tittyfucker", "tittys", "tittywank", 
"titwank", "tity", "tomurder", "toke",
    "tongethruster", "tongueina", "tonguethrust", "tonguetramp", "toots", 
"topless", "tortur", "torture", "tosser",
    "towelhead", "towelheads", "trailertrash", "tramp", "trannie", 
"tranny", "transsexual", "transvestite", "trashy",
    "tribadism", "triplex", "trisexual", "trots", "tubgirl", "tuckahoe", 
"turdburgler", "turnon", "tush", "tushy",
    "twat", "twathead", "twatlips", "twats", "twatty", "twatwaffle", 
"twink", "twinkie", "twunt", "twunter",
    "udgepacker", "ukrop", "unclefucker", "undressing", "unfuckable", 
"upskirt", "urethraplay", "urophilia",
    "usama", "ussys", "vagina", "vagiina", "valium", "venusmound", 
"vibrater", "vibrator", "violetwand", "virgin",
    "virginbreaker", "vittu", "vixen", "vjayjay", "vodka", "vomit", 
"vorarephilia", "voyeurweb", "voyuer", "vullva",
    "vulva", "wang", "wank", "wanker", "wanking", "wanky", "waysted", 
"wazoo", "weenie", "weewee", "weiner",
    "welcher", "wench", "wetdream", "wetb", "wetback", "wetbacks", 
"wetspot", "whacker", "whash", "whigger",
    "whiggers", "whiskeydick", "whiskydick", "whit", "whitepower", 
"whitenigger", "whites", "whitetrash", "whitey",
    "whiteys", "whities", "whoar", "whop", "whoralicious", "whore", 
"whorebag", "whored", "whoreface", "whorefucker",
    "whorehopper", "whorehouse", "whores", "whoring", "wichser", "wigga", 
"wiggas", "wigger", "wiggers", "willie",
    "willies", "williewanker", "willy", "wog", "wogs", "woose", "wop", 
"worldsex", "wrappingmen", "wrinkledstarfish",
    "wuss", "wuzzie", "yank", "yaoi", "yarpie", "yarpies", "yeasty", 
"yed", "yellowshowers", "yellowman", "yid",
    "yids", "yiffy", "yobbo", "yury", "zabourah", "zigabo", "zigabos", 
"zipperhead", "zipperheads", "zoophile",
    "zoophilia"
]

# Remove duplicates (already done, but included for robustness)
terms = list(dict.fromkeys(terms))

# Create a 34 x 33 grid
cols = 33
rows = (len(terms) + cols - 1) // cols
grid = [terms[i * cols:(i + 1) * cols] for i in range(rows)]

# Write to CSV
with open("terms.csv", "w", newline="") as f:
    writer = csv.writer(f, quoting=csv.QUOTE_ALL)
    writer.writerows(grid)
